# Generated by Django 4.2.16 on 2025-11-21 01:58

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('properties', '0001_initial'),
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reservation_type', models.CharField(choices=[('visit', 'Visite'), ('viewing', 'Visite avec achat'), ('purchase', 'Achat direct'), ('rent', 'Location'), ('evaluation', 'Évaluation')], default='viewing', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('confirmed', 'Confirmée'), ('cancelled', 'Annulée'), ('completed', 'Terminée'), ('expired', 'Expirée')], default='pending', max_length=20)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('currency', models.CharField(choices=[('XOF', 'Franc CFA (XOF)'), ('EUR', 'Euro (EUR)'), ('USD', 'Dollar US (USD)')], default='XOF', max_length=3)),
                ('scheduled_date', models.DateTimeField(blank=True, null=True)),
                ('scheduled_end_date', models.DateTimeField(blank=True, null=True)),
                ('duration_minutes', models.PositiveIntegerField(default=60)),
                ('purchase_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('reservation_deposit', models.DecimalField(blank=True, decimal_places=2, help_text='Montant de la réservation ou acompte', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('client_name', models.CharField(blank=True, max_length=200)),
                ('client_email', models.EmailField(blank=True, max_length=254)),
                ('client_phone', models.CharField(blank=True, max_length=20)),
                ('client_company', models.CharField(blank=True, max_length=200)),
                ('additional_participants', models.PositiveIntegerField(default=0)),
                ('participant_names', models.TextField(blank=True, help_text='Noms des participants supplémentaires')),
                ('special_requirements', models.TextField(blank=True, help_text='Besoins spéciaux, accessibilité, etc.')),
                ('language_preference', models.CharField(choices=[('fr', 'Français'), ('en', 'Anglais'), ('es', 'Espagnol'), ('de', 'Allemand'), ('it', 'Italien'), ('other', 'Autre')], default='fr', max_length=10)),
                ('preferred_contact_method', models.CharField(choices=[('email', 'Email'), ('phone', 'Téléphone'), ('sms', 'SMS'), ('whatsapp', 'WhatsApp')], default='email', max_length=20)),
                ('allow_sms_notifications', models.BooleanField(default=True)),
                ('allow_email_notifications', models.BooleanField(default=True)),
                ('client_notes', models.TextField(blank=True, help_text='Notes du client sur la réservation')),
                ('internal_notes', models.TextField(blank=True, help_text='Notes internes (non visibles par le client)')),
                ('cancellation_reason', models.TextField(blank=True)),
                ('completion_notes', models.TextField(blank=True)),
                ('payment_required', models.BooleanField(default=False, help_text='Cette réservation nécessite un paiement')),
                ('payment_status', models.CharField(choices=[('pending', 'Paiement en attente'), ('processing', 'Paiement en cours'), ('paid', 'Payé'), ('failed', 'Échec du paiement'), ('refunded', 'Remboursé')], default='pending', max_length=20)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('follow_up_required', models.BooleanField(default=False)),
                ('follow_up_date', models.DateTimeField(blank=True, null=True)),
                ('follow_up_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_reservations', to=settings.AUTH_USER_MODEL)),
                ('client_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='crm.clientprofile')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_reservations', to=settings.AUTH_USER_MODEL)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='properties.property')),
            ],
            options={
                'verbose_name': 'Réservation',
                'verbose_name_plural': 'Réservations',
                'db_table': 'reservations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stripe_payment_intent_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('stripe_charge_id', models.CharField(blank=True, max_length=100, null=True)),
                ('stripe_customer_id', models.CharField(blank=True, max_length=100, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('currency', models.CharField(choices=[('EUR', 'Euro (EUR)'), ('USD', 'Dollar US (USD)'), ('GBP', 'Livre Sterling (GBP)'), ('CHF', 'Franc Suisse (CHF)')], default='EUR', max_length=3)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('processing', 'En cours'), ('completed', 'Terminé'), ('failed', 'Échoué'), ('cancelled', 'Annulé'), ('refunded', 'Remboursé'), ('partial_refund', 'Remboursement partiel')], default='pending', max_length=20)),
                ('payment_method', models.CharField(choices=[('card', 'Carte bancaire'), ('bank_transfer', 'Virement bancaire'), ('paypal', 'PayPal'), ('apple_pay', 'Apple Pay'), ('google_pay', 'Google Pay'), ('cash', 'Espèces'), ('check', 'Chèque')], default='card', max_length=20)),
                ('card_brand', models.CharField(blank=True, help_text='Visa, Mastercard, etc.', max_length=20)),
                ('card_last_four', models.CharField(blank=True, help_text='4 derniers chiffres de la carte', max_length=4)),
                ('card_exp_month', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('card_exp_year', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(2020), django.core.validators.MaxValueValidator(2050)])),
                ('billing_name', models.CharField(blank=True, max_length=200)),
                ('billing_email', models.EmailField(blank=True, max_length=254)),
                ('billing_phone', models.CharField(blank=True, max_length=20)),
                ('billing_address_line1', models.CharField(blank=True, max_length=200)),
                ('billing_address_line2', models.CharField(blank=True, max_length=200)),
                ('billing_city', models.CharField(blank=True, max_length=100)),
                ('billing_postal_code', models.CharField(blank=True, max_length=20)),
                ('billing_country', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True, help_text='Description du paiement')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('processing_started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('failed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('error_code', models.CharField(blank=True, max_length=50)),
                ('error_message', models.TextField(blank=True)),
                ('failure_reason', models.TextField(blank=True)),
                ('refunded_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('refund_reason', models.TextField(blank=True)),
                ('refunded_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Métadonnées additionnelles (Stripe, système, etc.)')),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='reservations.reservation')),
            ],
            options={
                'verbose_name': 'Paiement',
                'verbose_name_plural': 'Paiements',
                'db_table': 'payments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReservationActivity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('activity_type', models.CharField(choices=[('created', 'Créé'), ('updated', 'Modifié'), ('status_changed', 'Statut modifié'), ('confirmed', 'Confirmé'), ('cancelled', 'Annulé'), ('completed', 'Terminé'), ('payment_created', 'Paiement créé'), ('payment_completed', 'Paiement complété'), ('payment_failed', 'Paiement échoué'), ('refund_created', 'Remboursement créé'), ('agent_assigned', 'Agent assigné'), ('notes_added', 'Notes ajoutées'), ('follow_up_scheduled', 'Suivi programmé')], max_length=30)),
                ('description', models.TextField()),
                ('old_value', models.TextField(blank=True)),
                ('new_value', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservation_activities', to=settings.AUTH_USER_MODEL)),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='reservations.reservation')),
            ],
            options={
                'verbose_name': 'Activité de Réservation',
                'verbose_name_plural': 'Activités de Réservation',
                'db_table': 'reservation_activities',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['reservation', 'created_at'], name='reservation_reserva_d8d0de_idx'), models.Index(fields=['activity_type'], name='reservation_activit_da7a00_idx'), models.Index(fields=['performed_by'], name='reservation_perform_c8e3dd_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['property', 'status'], name='reservation_propert_d535e8_idx'),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['client_profile'], name='reservation_client__47cb53_idx'),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['assigned_agent'], name='reservation_assigne_be682d_idx'),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['scheduled_date'], name='reservation_schedul_079b28_idx'),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['status', 'scheduled_date'], name='reservation_status_3f4b43_idx'),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['payment_status'], name='reservation_payment_98b457_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['reservation'], name='payments_reserva_5bfdcf_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['stripe_payment_intent_id'], name='payments_stripe__6cb0ea_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['status'], name='payments_status_d621e5_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['created_at'], name='payments_created_e3a130_idx'),
        ),
    ]
