# Generated by Django 4.2.16 on 2026-02-23 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservations", "0002_add_contract_and_template"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="contract",
            new_name="contracts_reserva_ff1969_idx",
            old_name="contracts_reservat_idx",
        ),
        migrations.RenameIndex(
            model_name="contract",
            new_name="contracts_status_093df1_idx",
            old_name="contracts_status_idx",
        ),
        migrations.RenameIndex(
            model_name="contract",
            new_name="contracts_contrac_6a8e6a_idx",
            old_name="contracts_contract_idx",
        ),
        migrations.AlterField(
            model_name="reservationactivity",
            name="activity_type",
            field=models.CharField(
                choices=[
                    ("created", "Créé"),
                    ("updated", "Modifié"),
                    ("status_changed", "Statut modifié"),
                    ("confirmed", "Confirmé"),
                    ("cancelled", "Annulé"),
                    ("completed", "Terminé"),
                    ("payment_created", "Paiement créé"),
                    ("payment_completed", "Paiement complété"),
                    ("payment_failed", "Paiement échoué"),
                    ("refund_created", "Remboursement créé"),
                    ("agent_assigned", "Agent assigné"),
                    ("notes_added", "Notes ajoutées"),
                    ("follow_up_scheduled", "Suivi programmé"),
                    ("contract_created", "Contrat créé"),
                    ("contract_sent", "Contrat envoyé"),
                    ("contract_signed", "Contrat signé"),
                ],
                max_length=30,
            ),
        ),
    ]
