# Generated by Django 4.2.16 on 2026-02-24 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reservations", "0004_contract_verification_code_viewed_at"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="contract",
            new_name="contracts_verific_bcc086_idx",
            old_name="contracts_verific_idx",
        ),
    ]
