# Generated by Django 4.2.16 on 2025-12-06 13:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crm', '0002_initial'),
        ('properties', '0003_add_property_amenities_features'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('conversation_type', models.CharField(choices=[('direct', 'Direct'), ('group', 'Groupe'), ('client_agent', 'Client-Agent'), ('agent_agent', 'Agent-Agent')], default='direct', help_text='Type de conversation', max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text='Conversation active')),
                ('is_archived', models.BooleanField(default=False, help_text='Conversation archivée')),
                ('last_message', models.TextField(blank=True, help_text='Dernier message')),
                ('last_message_at', models.DateTimeField(blank=True, help_text='Date du dernier message', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(blank=True, help_text='Client associé (si conversation client-agent)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversations', to='crm.clientprofile')),
                ('last_message_by', models.ForeignKey(blank=True, help_text='Auteur du dernier message', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_messages', to=settings.AUTH_USER_MODEL)),
                ('participants', models.ManyToManyField(help_text='Participants de la conversation', related_name='conversations', to=settings.AUTH_USER_MODEL)),
                ('property', models.ForeignKey(blank=True, help_text='Propriété associée à la conversation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversations', to='properties.property')),
            ],
            options={
                'verbose_name': 'Conversation',
                'verbose_name_plural': 'Conversations',
                'db_table': 'agent_conversations',
                'ordering': ['-last_message_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('message_type', models.CharField(choices=[('text', 'Texte'), ('image', 'Image'), ('file', 'Fichier'), ('system', 'Système')], default='text', help_text='Type de message', max_length=20)),
                ('content', models.TextField(help_text='Contenu du message')),
                ('image', models.ImageField(blank=True, help_text='Image attachée', null=True, upload_to='messages/images/')),
                ('file', models.FileField(blank=True, help_text='Fichier attaché', null=True, upload_to='messages/files/')),
                ('read_at', models.DateTimeField(blank=True, help_text='Date de lecture', null=True)),
                ('is_edited', models.BooleanField(default=False, help_text='Message modifié')),
                ('is_deleted', models.BooleanField(default=False, help_text='Message supprimé')),
                ('edited_at', models.DateTimeField(blank=True, help_text='Date de modification', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('conversation', models.ForeignKey(help_text='Conversation parente', on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='messaging.conversation')),
                ('read_by', models.ForeignKey(blank=True, help_text='Utilisateur qui a lu le message', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='read_messages', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(help_text='Expéditeur du message', on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
                'db_table': 'agent_messages',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['conversation', 'created_at'], name='agent_messa_convers_7ad657_idx'), models.Index(fields=['sender', 'created_at'], name='agent_messa_sender__3d6e20_idx'), models.Index(fields=['read_by', 'read_at'], name='agent_messa_read_by_2276b0_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['conversation_type', 'is_active'], name='agent_conve_convers_e54b26_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['last_message_at'], name='agent_conve_last_me_1d06ed_idx'),
        ),
    ]
