# Generated by Django 4.2.16 on 2025-12-05 18:35

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0003_add_property_amenities_features'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('custom_auth', '0001_initial'),
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('commission_type', models.CharField(choices=[('sale', 'Vente'), ('rental', 'Location'), ('referral', 'Référence'), ('bonus', 'Bonus')], default='sale', max_length=20)),
                ('base_amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('commission_rate', models.DecimalField(decimal_places=2, default=Decimal('3.00'), help_text='Taux de commission en pourcentage', max_digits=5)),
                ('commission_amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('approved', 'Approuvée'), ('paid', 'Payée'), ('cancelled', 'Annulée')], default='pending', max_length=20)),
                ('transaction_date', models.DateTimeField(blank=True, help_text='Date de la transaction (vente/location)', null=True)),
                ('approved_date', models.DateTimeField(blank=True, null=True)),
                ('paid_date', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commissions', to='custom_auth.agency')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commissions', to=settings.AUTH_USER_MODEL)),
                ('property', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commissions', to='properties.property')),
                ('reservation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commissions', to='reservations.reservation')),
            ],
            options={
                'verbose_name': 'Commission',
                'verbose_name_plural': 'Commissions',
                'db_table': 'agent_commissions',
                'ordering': ['-transaction_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('payment_method', models.CharField(choices=[('bank_transfer', 'Virement bancaire'), ('mobile_money', 'Mobile Money'), ('cash', 'Espèces'), ('check', 'Chèque'), ('other', 'Autre')], default='bank_transfer', max_length=20)),
                ('payment_reference', models.CharField(blank=True, help_text='Référence de paiement', max_length=200)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('processing', 'En traitement'), ('completed', 'Complété'), ('failed', 'Échoué'), ('cancelled', 'Annulé')], default='pending', max_length=20)),
                ('payment_date', models.DateTimeField(blank=True, null=True)),
                ('processed_date', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='custom_auth.agency')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL)),
                ('commissions', models.ManyToManyField(blank=True, related_name='payments', to='commissions.commission')),
            ],
            options={
                'verbose_name': 'Paiement Commission',
                'verbose_name_plural': 'Paiements Commissions',
                'db_table': 'commission_payments',
                'ordering': ['-payment_date', '-created_at'],
                'indexes': [models.Index(fields=['agent', 'status'], name='commission__agent_i_85cf50_idx'), models.Index(fields=['agency', 'status'], name='commission__agency__f6e7ac_idx'), models.Index(fields=['payment_date'], name='commission__payment_bb2c9b_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='commission',
            index=models.Index(fields=['agent', 'status'], name='agent_commi_agent_i_0bd943_idx'),
        ),
        migrations.AddIndex(
            model_name='commission',
            index=models.Index(fields=['agency', 'status'], name='agent_commi_agency__e5d61c_idx'),
        ),
        migrations.AddIndex(
            model_name='commission',
            index=models.Index(fields=['transaction_date'], name='agent_commi_transac_e283c4_idx'),
        ),
    ]
