# Generated by Django 4.2.16 on 2025-11-24 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='property_type_display',
            field=models.CharField(choices=[('sale', 'Vente'), ('rent', 'Location')], default='sale', max_length=20),
        ),
    ]
