# Generated by Django 4.2.16 on 2025-12-03 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_property_property_type_display'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='has_baby_crib',
            field=models.BooleanField(default=False, verbose_name='Lit pour bébé'),
        ),
        migrations.AddField(
            model_name='property',
            name='has_backyard',
            field=models.BooleanField(default=False, verbose_name='Arrière-cour'),
        ),
        migrations.AddField(
            model_name='property',
            name='has_basic_kitchen_equipment',
            field=models.BooleanField(default=False, verbose_name='Équipements de cuisine de base'),
        ),
        migrations.AddField(
            model_name='property',
            name='has_bathtub',
            field=models.BooleanField(default=False, verbose_name='Baignoire'),
        ),
        migrations.AddField(
            model_name='property',
            name='has_blender',
            field=models.BooleanField(default=False, verbose_name='Blender'),
        ),
        migrations.AddField(
            model_name='property',
            name='has_blinds',
            field=models.BooleanField(default=False, verbose_name='Stores'),
        ),
        migrations.AddField(
            model_name='property',
            name='has_carbon_monoxide_detector',
            field=models.BooleanField(default=False, verbose_name='Détecteur de monoxyde de carbone'),
        ),
        migrations.AddField(
            model_name='property',
            name='has_children_playroom',
            field=models.BooleanField(default=False, verbose_name='Salle de jeux pour enfants'),
        ),
        migrations.AddField(
            model_name='property',
            name='has_cleaning_during_stay',
            field=models.BooleanField(default=False, verbose_name='Ménage disponible pendant le séjour'),
        ),
        migrations.AddField(
            model_name='property',
            name='has_clothes_rack',
            field=models.BooleanField(default=False, verbose_name='Étendoir à linge'),
        ),
        migrations.AddField(
            model_name='property',
            name='has_clothes_storage',
            field=models.BooleanField(default=False, verbose_name='Espace de rangement pour les vêtements'),
        ),
        migrations.AddField(
            model_name='property',
            name='has_coffee_maker',
            field=models.BooleanField(default=False, verbose_name='Cafetière'),
        ),
        migrations.AddField(
            model_name='property',
            name='has_dining_table',
            field=models.BooleanField(default=False, verbose_name='Table à manger'),
        ),
        migrations.AddField(
            model_name='property',
            name='has_dishes_utensils',
            field=models.BooleanField(default=False, verbose_name='Vaisselle et couverts'),
        ),
        migrations.AddField(
            model_name='property',
            name='has_dishwasher',
            field=models.BooleanField(default=False, verbose_name='Lave-vaisselle'),
        ),
        migrations.AddField(
            model_name='property',
            name='has_dryer',
            field=models.BooleanField(default=False, verbose_name='Sèche-linge'),
        ),
        migrations.AddField(
            model_name='property',
            name='has_essentials',
            field=models.BooleanField(default=False, verbose_name='Serviettes, draps, savon et papier toilette'),
        ),
        migrations.AddField(
            model_name='property',
            name='has_extra_pillows_blankets',
            field=models.BooleanField(default=False, verbose_name='Oreillers et couvertures supplémentaires'),
        ),
        migrations.AddField(
            model_name='property',
            name='has_free_parking_on_premises',
            field=models.BooleanField(default=False, verbose_name='Parking gratuit sur place'),
        ),
        migrations.AddField(
            model_name='property',
            name='has_free_street_parking',
            field=models.BooleanField(default=False, verbose_name='Parking gratuit dans la rue'),
        ),
        migrations.AddField(
            model_name='property',
            name='has_freezer',
            field=models.BooleanField(default=False, verbose_name='Congélateur'),
        ),
        migrations.AddField(
            model_name='property',
            name='has_hangers',
            field=models.BooleanField(default=False, verbose_name='Cintres'),
        ),
        migrations.AddField(
            model_name='property',
            name='has_heating',
            field=models.BooleanField(default=False, verbose_name='Chauffage'),
        ),
        migrations.AddField(
            model_name='property',
            name='has_hot_water',
            field=models.BooleanField(default=True, verbose_name='Eau chaude'),
        ),
        migrations.AddField(
            model_name='property',
            name='has_iron',
            field=models.BooleanField(default=False, verbose_name='Fer à repasser'),
        ),
        migrations.AddField(
            model_name='property',
            name='has_key_exchange_by_host',
            field=models.BooleanField(default=False, verbose_name="Clés remises par l'hôte"),
        ),
        migrations.AddField(
            model_name='property',
            name='has_kitchen',
            field=models.BooleanField(default=False, verbose_name='Cuisine'),
        ),
        migrations.AddField(
            model_name='property',
            name='has_long_term_stays_allowed',
            field=models.BooleanField(default=False, verbose_name='Séjours longue durée autorisés'),
        ),
        migrations.AddField(
            model_name='property',
            name='has_lounge_chairs',
            field=models.BooleanField(default=False, verbose_name='Chaises longues'),
        ),
        migrations.AddField(
            model_name='property',
            name='has_luggage_dropoff_allowed',
            field=models.BooleanField(default=False, verbose_name='Dépôt de bagages autorisé'),
        ),
        migrations.AddField(
            model_name='property',
            name='has_microwave',
            field=models.BooleanField(default=False, verbose_name='Four à micro-ondes'),
        ),
        migrations.AddField(
            model_name='property',
            name='has_outdoor_dining_space',
            field=models.BooleanField(default=False, verbose_name='Espace repas en plein air'),
        ),
        migrations.AddField(
            model_name='property',
            name='has_outdoor_furniture',
            field=models.BooleanField(default=False, verbose_name="Mobilier d'extérieur"),
        ),
        migrations.AddField(
            model_name='property',
            name='has_outdoor_kitchen',
            field=models.BooleanField(default=False, verbose_name='Cuisine extérieure'),
        ),
        migrations.AddField(
            model_name='property',
            name='has_outdoor_security_cameras',
            field=models.BooleanField(default=False, verbose_name='Caméras de surveillance extérieures'),
        ),
        migrations.AddField(
            model_name='property',
            name='has_outdoor_shower',
            field=models.BooleanField(default=False, verbose_name='Douche extérieure'),
        ),
        migrations.AddField(
            model_name='property',
            name='has_oven',
            field=models.BooleanField(default=False, verbose_name='Four'),
        ),
        migrations.AddField(
            model_name='property',
            name='has_portable_fans',
            field=models.BooleanField(default=False, verbose_name='Ventilateurs portables'),
        ),
        migrations.AddField(
            model_name='property',
            name='has_portable_wifi',
            field=models.BooleanField(default=False, verbose_name='Wi-Fi portable'),
        ),
        migrations.AddField(
            model_name='property',
            name='has_refrigerator',
            field=models.BooleanField(default=False, verbose_name='Réfrigérateur'),
        ),
        migrations.AddField(
            model_name='property',
            name='has_security_cameras',
            field=models.BooleanField(default=False, verbose_name="Présence de caméras à l'extérieur"),
        ),
        migrations.AddField(
            model_name='property',
            name='has_sheets',
            field=models.BooleanField(default=False, verbose_name='Draps'),
        ),
        migrations.AddField(
            model_name='property',
            name='has_smoke_detector',
            field=models.BooleanField(default=False, verbose_name='Détecteur de fumée'),
        ),
        migrations.AddField(
            model_name='property',
            name='has_stove',
            field=models.BooleanField(default=False, verbose_name='Cuisinière'),
        ),
        migrations.AddField(
            model_name='property',
            name='has_tv',
            field=models.BooleanField(default=False, verbose_name='Télévision'),
        ),
        migrations.AddField(
            model_name='property',
            name='has_washing_machine',
            field=models.BooleanField(default=False, verbose_name='Lave-linge'),
        ),
        migrations.AddField(
            model_name='property',
            name='has_wifi',
            field=models.BooleanField(default=False, verbose_name='WiFi'),
        ),
        migrations.AddField(
            model_name='property',
            name='has_year_round_pool',
            field=models.BooleanField(default=False, verbose_name="Piscine privée disponible toute l'année"),
        ),
        migrations.AlterField(
            model_name='property',
            name='has_air_conditioning',
            field=models.BooleanField(default=False, verbose_name='Climatisation'),
        ),
        migrations.AlterField(
            model_name='property',
            name='has_balcony',
            field=models.BooleanField(default=False, verbose_name='Balcon'),
        ),
        migrations.AlterField(
            model_name='property',
            name='has_elevator',
            field=models.BooleanField(default=False, verbose_name='Ascenseur'),
        ),
        migrations.AlterField(
            model_name='property',
            name='has_fireplace',
            field=models.BooleanField(default=False, verbose_name='Cheminée'),
        ),
        migrations.AlterField(
            model_name='property',
            name='has_garage',
            field=models.BooleanField(default=False, verbose_name='Garage'),
        ),
        migrations.AlterField(
            model_name='property',
            name='has_garden',
            field=models.BooleanField(default=False, verbose_name='Jardin'),
        ),
        migrations.AlterField(
            model_name='property',
            name='has_parking',
            field=models.BooleanField(default=False, verbose_name='Parking'),
        ),
        migrations.AlterField(
            model_name='property',
            name='has_pool',
            field=models.BooleanField(default=False, verbose_name='Piscine'),
        ),
        migrations.AlterField(
            model_name='property',
            name='has_security_system',
            field=models.BooleanField(default=False, verbose_name='Système de sécurité'),
        ),
        migrations.AlterField(
            model_name='property',
            name='has_terrace',
            field=models.BooleanField(default=False, verbose_name='Terrasse'),
        ),
    ]
