# Generated by Django 4.2.16 on 2025-11-21 01:58

import django.core.validators
from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientInteraction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('interaction_type', models.CharField(choices=[('call', 'Appel téléphonique'), ('email', 'Email'), ('sms', 'SMS'), ('meeting', 'Rendez-vous'), ('visit', 'Visite'), ('inquiry', "Demande d'informations"), ('follow_up', 'Relance'), ('complaint', 'Réclamation'), ('feedback', 'Retour client')], max_length=20)),
                ('channel', models.CharField(choices=[('phone', 'Téléphone'), ('email', 'Email'), ('sms', 'SMS'), ('whatsapp', 'WhatsApp'), ('in_person', 'En personne'), ('video_call', 'Appel vidéo'), ('portal', 'Portail client')], max_length=20)),
                ('subject', models.CharField(blank=True, max_length=200)),
                ('content', models.TextField()),
                ('outcome', models.CharField(blank=True, choices=[('successful', 'Réussi'), ('unsuccessful', 'Échoué'), ('callback_requested', 'Rappel demandé'), ('follow_up_required', 'Suivi requis'), ('meeting_scheduled', 'Rendez-vous programmé'), ('no_response', 'Pas de réponse')], max_length=20)),
                ('scheduled_date', models.DateTimeField(blank=True, null=True)),
                ('completed_date', models.DateTimeField(blank=True, null=True)),
                ('duration_minutes', models.IntegerField(blank=True, null=True)),
                ('object_id', models.UUIDField(blank=True, null=True)),
                ('requires_follow_up', models.BooleanField(default=False)),
                ('follow_up_date', models.DateTimeField(blank=True, null=True)),
                ('follow_up_completed', models.BooleanField(default=False)),
                ('priority', models.CharField(choices=[('low', 'Faible'), ('medium', 'Moyen'), ('high', 'Élevé'), ('urgent', 'Urgent')], default='medium', max_length=20)),
                ('status', models.CharField(choices=[('scheduled', 'Programmée'), ('in_progress', 'En cours'), ('completed', 'Terminée'), ('cancelled', 'Annulée'), ('no_show', 'Absent')], default='scheduled', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Interaction Client',
                'verbose_name_plural': 'Interactions Clients',
                'db_table': 'crm_client_interaction',
                'ordering': ['-scheduled_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClientProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('nationality', models.CharField(blank=True, max_length=100)),
                ('marital_status', models.CharField(blank=True, choices=[('single', 'Célibataire'), ('married', 'Marié(e)'), ('divorced', 'Divorcé(e)'), ('widowed', 'Veuf/Veuve'), ('partnership', 'Union civile')], max_length=20)),
                ('preferred_contact_method', models.CharField(choices=[('email', 'Email'), ('phone', 'Téléphone'), ('sms', 'SMS'), ('whatsapp', 'WhatsApp')], default='email', max_length=20)),
                ('preferred_contact_time', models.CharField(choices=[('morning', 'Matin (8h-12h)'), ('afternoon', 'Après-midi (12h-18h)'), ('evening', 'Soirée (18h-20h)'), ('anytime', 'À tout moment')], default='anytime', max_length=50)),
                ('max_budget', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('min_budget', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('preferred_property_types', models.JSONField(blank=True, default=list)),
                ('preferred_locations', models.JSONField(blank=True, default=list)),
                ('min_bedrooms', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('max_bedrooms', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('min_area', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('max_area', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('preferred_cities', models.JSONField(blank=True, default=list)),
                ('max_distance_from_center', models.IntegerField(default=10, help_text='Distance maximale du centre-ville en km')),
                ('financing_status', models.CharField(choices=[('cash', 'Financement personnel'), ('mortgage', 'Prêt immobilier'), ('not_sure', 'Non défini'), ('pre_approved', 'Pré-approbation obtenue')], default='not_sure', max_length=20)),
                ('credit_score_range', models.CharField(choices=[('excellent', 'Excellent (750+)'), ('good', 'Bon (650-749)'), ('fair', 'Moyen (600-649)'), ('poor', 'Faible (<600)'), ('unknown', 'Inconnu')], default='unknown', max_length=20)),
                ('must_have_features', models.JSONField(blank=True, default=list)),
                ('deal_breakers', models.JSONField(blank=True, default=list)),
                ('lifestyle_notes', models.TextField(blank=True, help_text='Notes sur le mode de vie, habitudes, etc.')),
                ('status', models.CharField(choices=[('active', 'Actif'), ('inactive', 'Inactif'), ('prospect', 'Prospect'), ('client', 'Client'), ('archived', 'Archivé')], default='prospect', max_length=20)),
                ('priority_level', models.CharField(choices=[('low', 'Faible'), ('medium', 'Moyen'), ('high', 'Élevé'), ('urgent', 'Urgent')], default='medium', max_length=20)),
                ('last_property_view', models.DateTimeField(blank=True, null=True)),
                ('total_properties_viewed', models.IntegerField(default=0)),
                ('total_inquiries_made', models.IntegerField(default=0)),
                ('conversion_score', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Profil Client',
                'verbose_name_plural': 'Profils Clients',
                'db_table': 'crm_client_profile',
            },
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('company', models.CharField(blank=True, max_length=200)),
                ('source', models.CharField(choices=[('website', 'Site web'), ('referral', 'Référence'), ('social_media', 'Réseaux sociaux'), ('advertisement', 'Publicité'), ('walk_in', 'Visite directe'), ('phone_call', 'Appel téléphonique'), ('email', 'Email'), ('open_house', 'Journée portes ouvertes'), ('partner', 'Partenaire'), ('other', 'Autre')], max_length=20)),
                ('status', models.CharField(choices=[('new', 'Nouveau'), ('contacted', 'Contacté'), ('qualified', 'Qualifié'), ('proposal_sent', 'Proposition envoyée'), ('negotiation', 'En négociation'), ('won', 'Converti'), ('lost', 'Perdu'), ('archived', 'Archivé')], default='new', max_length=20)),
                ('qualification', models.CharField(choices=[('hot', 'Brûlant'), ('warm', 'Tiède'), ('cold', 'Froid'), ('unqualified', 'Non qualifié')], default='cold', max_length=20)),
                ('property_type_interest', models.CharField(blank=True, max_length=50)),
                ('budget_range', models.CharField(blank=True, max_length=100)),
                ('location_interest', models.CharField(blank=True, max_length=200)),
                ('timeframe', models.CharField(blank=True, help_text="Délai souhaité pour l'achat/location", max_length=50)),
                ('score', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('notes', models.TextField(blank=True)),
                ('next_action', models.CharField(blank=True, max_length=200)),
                ('next_action_date', models.DateTimeField(blank=True, null=True)),
                ('converted_to_client', models.BooleanField(default=False)),
                ('conversion_date', models.DateTimeField(blank=True, null=True)),
                ('lost_reason', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Lead',
                'verbose_name_plural': 'Leads',
                'db_table': 'crm_lead',
                'ordering': ['-score', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PropertyInterest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('interaction_type', models.CharField(choices=[('view', 'Vue'), ('favorite', 'Favori'), ('inquiry', "Demande d'informations"), ('visit_request', 'Demande de visite'), ('visit_scheduled', 'Visite programmée'), ('offer_made', 'Offre soumise'), ('offer_rejected', 'Offre refusée'), ('purchase_completed', 'Achat complété')], max_length=20)),
                ('interaction_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True)),
                ('interest_level', models.CharField(choices=[('low', 'Faible'), ('medium', 'Moyen'), ('high', 'Élevé'), ('very_high', 'Très élevé')], default='medium', max_length=20)),
                ('match_score', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('status', models.CharField(choices=[('active', 'Actif'), ('archived', 'Archivé'), ('converted', 'Converti'), ('lost', 'Perdu')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Intérêt Propriété',
                'verbose_name_plural': 'Intérêts Propriétés',
                'db_table': 'crm_property_interest',
                'ordering': ['-interaction_date'],
            },
        ),
    ]
