# Generated by Django 4.2.16 on 2025-11-21 01:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('custom_auth', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyinterest',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_interests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='propertyinterest',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_interests', to='properties.property'),
        ),
        migrations.AddField(
            model_name='lead',
            name='agency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='custom_auth.agency'),
        ),
        migrations.AddField(
            model_name='lead',
            name='assigned_agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_leads', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='client_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='clientinteraction',
            name='agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_interactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='clientinteraction',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='clientinteraction',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AlterUniqueTogether(
            name='propertyinterest',
            unique_together={('client', 'property')},
        ),
    ]
