# Generated by Django 5.2.6 on 2026-02-05 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_add_client_notes_and_tags'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='clientnote',
            new_name='crm_clientn_client__2d3a8a_idx',
            old_name='crm_clientn_client__idx',
        ),
        migrations.RenameIndex(
            model_name='clientnote',
            new_name='crm_clientn_author__1c7d8c_idx',
            old_name='crm_clientn_author_idx',
        ),
    ]
