# Generated by Django 4.2.16 on 2025-11-21 01:58

import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarConflict',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('conflict_type', models.CharField(max_length=50)),
                ('severity', models.CharField(choices=[('low', 'Faible'), ('medium', 'Moyenne'), ('high', 'Élevée'), ('critical', 'Critique')], max_length=20)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('detected', 'Détecté'), ('resolved', 'Résolu'), ('ignored', 'Ignoré')], default='detected', max_length=20)),
                ('resolution_notes', models.TextField(blank=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'calendar_conflict',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClientAvailability',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('preferred_date', models.DateField()),
                ('preferred_time_slot', models.CharField(choices=[('morning', 'Matin'), ('afternoon', 'Après-midi'), ('evening', 'Soirée'), ('any', 'Indifférent')], max_length=20)),
                ('specific_start_time', models.TimeField(blank=True, null=True)),
                ('specific_end_time', models.TimeField(blank=True, null=True)),
                ('urgency', models.CharField(choices=[('low', 'Basse'), ('normal', 'Normale'), ('high', 'Haute'), ('urgent', 'Urgente')], default='normal', max_length=20)),
                ('preferred_duration', models.PositiveIntegerField(default=60, validators=[django.core.validators.MinValueValidator(15), django.core.validators.MaxValueValidator(240)])),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'client_availability',
                'ordering': ['preferred_date', 'user'],
            },
        ),
        migrations.CreateModel(
            name='ScheduleMetrics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('total_scheduled_visits', models.PositiveIntegerField(default=0)),
                ('completed_visits', models.PositiveIntegerField(default=0)),
                ('cancelled_visits', models.PositiveIntegerField(default=0)),
                ('no_show_visits', models.PositiveIntegerField(default=0)),
                ('average_match_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('total_travel_time', models.PositiveIntegerField(default=0, help_text='Minutes')),
                ('total_distance', models.DecimalField(decimal_places=2, default=0, help_text='km', max_digits=10)),
                ('optimization_savings', models.DecimalField(blank=True, decimal_places=2, help_text='Minutes économisées', max_digits=8, null=True)),
                ('efficiency_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'schedule_metrics',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='SchedulingPreference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('route_optimization', models.CharField(choices=[('none', 'Aucune'), ('distance', 'Par distance'), ('time', 'Par temps de trajet'), ('fuel', 'Économie de carburant')], default='time', max_length=20)),
                ('client_preference_handling', models.CharField(choices=[('ignore', 'Ignorer'), ('consider', 'Considérer'), ('prioritize', 'Prioriser')], default='consider', max_length=20)),
                ('max_daily_visits', models.PositiveIntegerField(default=8)),
                ('min_break_minutes', models.PositiveIntegerField(default=30)),
                ('travel_time_buffer', models.PositiveIntegerField(default=15, help_text='Minutes de marge pour les trajets')),
                ('working_radius', models.DecimalField(blank=True, decimal_places=2, help_text='Rayon de travail en km', max_digits=8, null=True)),
                ('preferred_areas', models.JSONField(default=list, help_text='Zones de travail préférées (codes postaux, villes)')),
                ('preferred_property_types', models.JSONField(default=list, help_text='Types de propriétés préférées')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'scheduling_preference',
            },
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('status', models.CharField(choices=[('available', 'Disponible'), ('booked', 'Réservé'), ('blocked', 'Bloqué'), ('holiday', 'Congé'), ('sick', 'Malade')], default='available', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'time_slot',
                'ordering': ['date', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='VisitSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scheduled_date', models.DateField()),
                ('scheduled_start_time', models.TimeField()),
                ('scheduled_end_time', models.TimeField()),
                ('matching_algorithm', models.CharField(choices=[('first_available', 'Premier disponible'), ('best_match', 'Meilleure correspondance'), ('optimal_route', 'Route optimale'), ('load_balancing', 'Répartition de charge')], default='best_match', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('scheduled', 'Planifiée'), ('confirmed', 'Confirmée'), ('in_progress', 'En cours'), ('completed', 'Terminée'), ('cancelled', 'Annulée'), ('no_show', 'Absent')], default='pending', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Basse'), ('normal', 'Normale'), ('high', 'Haute'), ('urgent', 'Urgente')], default='normal', max_length=20)),
                ('match_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('match_factors', models.JSONField(default=dict)),
                ('travel_time', models.PositiveIntegerField(blank=True, help_text='Temps de trajet en minutes', null=True)),
                ('distance', models.DecimalField(blank=True, decimal_places=2, help_text='Distance en km', max_digits=8, null=True)),
                ('client_notes', models.TextField(blank=True)),
                ('agent_notes', models.TextField(blank=True)),
                ('system_notes', models.TextField(blank=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'visit_schedule',
                'ordering': ['scheduled_date', 'scheduled_start_time'],
            },
        ),
        migrations.CreateModel(
            name='WorkingHours',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('day_of_week', models.IntegerField(choices=[(0, 'Lundi'), (1, 'Mardi'), (2, 'Mercredi'), (3, 'Jeudi'), (4, 'Vendredi'), (5, 'Samedi'), (6, 'Dimanche')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_working', models.BooleanField(default=True)),
                ('break_start', models.TimeField(blank=True, null=True)),
                ('break_end', models.TimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'working_hours',
                'ordering': ['user', 'day_of_week'],
            },
        ),
    ]
