# Generated by Django 4.2.16 on 2025-11-21 01:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reservations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('properties', '0001_initial'),
        ('calendar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workinghours',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='working_hours', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='visitschedule',
            name='agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_agent_visits', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='visitschedule',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_visits', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='visitschedule',
            name='confirmed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_schedules', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='visitschedule',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_visits', to='properties.property'),
        ),
        migrations.AddField(
            model_name='visitschedule',
            name='reservation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='schedule', to='reservations.reservation'),
        ),
        migrations.AddField(
            model_name='timeslot',
            name='reservation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='time_slots', to='reservations.reservation'),
        ),
        migrations.AddField(
            model_name='timeslot',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_slots', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='schedulingpreference',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='scheduling_preferences', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='schedulemetrics',
            name='agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_metrics', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='clientavailability',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_availabilities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='calendarconflict',
            name='resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_conflicts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='calendarconflict',
            name='schedule1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conflicts_as_first', to='calendar.visitschedule'),
        ),
        migrations.AddField(
            model_name='calendarconflict',
            name='schedule2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conflicts_as_second', to='calendar.visitschedule'),
        ),
        migrations.AlterUniqueTogether(
            name='workinghours',
            unique_together={('user', 'day_of_week')},
        ),
        migrations.AddIndex(
            model_name='visitschedule',
            index=models.Index(fields=['agent', 'scheduled_date', 'status'], name='visit_sched_agent_i_e18caa_idx'),
        ),
        migrations.AddIndex(
            model_name='visitschedule',
            index=models.Index(fields=['client', 'status'], name='visit_sched_client__4ec937_idx'),
        ),
        migrations.AddIndex(
            model_name='visitschedule',
            index=models.Index(fields=['property', 'status'], name='visit_sched_propert_5e8be7_idx'),
        ),
        migrations.AddIndex(
            model_name='timeslot',
            index=models.Index(fields=['user', 'date', 'status'], name='time_slot_user_id_e7042b_idx'),
        ),
        migrations.AddIndex(
            model_name='timeslot',
            index=models.Index(fields=['date', 'status'], name='time_slot_date_42aba8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='timeslot',
            unique_together={('user', 'date', 'start_time', 'end_time')},
        ),
        migrations.AlterUniqueTogether(
            name='schedulemetrics',
            unique_together={('date', 'agent')},
        ),
        migrations.AddIndex(
            model_name='clientavailability',
            index=models.Index(fields=['preferred_date', 'user', 'is_active'], name='client_avai_preferr_84accf_idx'),
        ),
        migrations.AddIndex(
            model_name='calendarconflict',
            index=models.Index(fields=['status', 'severity'], name='calendar_co_status_a5f7b3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='calendarconflict',
            unique_together={('schedule1', 'schedule2', 'conflict_type')},
        ),
    ]
