# Generated by Django 5.2.6 on 2026-02-04 23:47

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0003_add_property_amenities_features'),
        ('reservations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('review_type', models.CharField(choices=[('property', 'Avis sur bien'), ('agent', 'Avis sur agent'), ('reservation', 'Avis sur réservation'), ('visit', 'Avis après visite')], max_length=20)),
                ('rating', models.PositiveIntegerField(help_text='Note de 1 à 5 étoiles', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('title', models.CharField(blank=True, help_text="Titre de l'avis", max_length=200)),
                ('comment', models.TextField(help_text='Commentaire détaillé')),
                ('rating_communication', models.PositiveIntegerField(blank=True, help_text='Note pour la communication', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('rating_professionalism', models.PositiveIntegerField(blank=True, help_text='Note pour le professionnalisme', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('rating_value', models.PositiveIntegerField(blank=True, help_text='Note pour le rapport qualité/prix', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('rating_cleanliness', models.PositiveIntegerField(blank=True, help_text='Note pour la propreté (bien)', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('rating_location', models.PositiveIntegerField(blank=True, help_text="Note pour l'emplacement (bien)", null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('is_published', models.BooleanField(default=False, help_text='Avis publié et visible')),
                ('is_verified', models.BooleanField(default=False, help_text='Avis vérifié (client a effectué une réservation)')),
                ('moderated_at', models.DateTimeField(blank=True, null=True)),
                ('moderation_notes', models.TextField(blank=True)),
                ('response', models.TextField(blank=True, help_text="Réponse de l'agent/propriétaire")),
                ('response_date', models.DateTimeField(blank=True, null=True)),
                ('helpful_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(blank=True, help_text='Agent concerné', limit_choices_to={'role__in': ['agent', 'manager']}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews_received', to=settings.AUTH_USER_MODEL)),
                ('author', models.ForeignKey(help_text="Client qui a écrit l'avis", on_delete=django.db.models.deletion.CASCADE, related_name='reviews_written', to=settings.AUTH_USER_MODEL)),
                ('moderated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews_moderated', to=settings.AUTH_USER_MODEL)),
                ('property', models.ForeignKey(blank=True, help_text='Bien immobilier concerné', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='properties.property')),
                ('reservation', models.ForeignKey(blank=True, help_text='Réservation concernée', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='reservations.reservation')),
                ('response_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='review_responses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReviewHelpful',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='helpful_votes', to='reviews.review')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='helpful_review_votes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['property', 'is_published'], name='reviews_rev_propert_e9ea18_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['agent', 'is_published'], name='reviews_rev_agent_i_4c6dfb_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['author'], name='reviews_rev_author__84fa2f_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['-created_at'], name='reviews_rev_created_03e07d_idx'),
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.UniqueConstraint(condition=models.Q(('reservation__isnull', False)), fields=('author', 'reservation'), name='unique_review_per_reservation'),
        ),
        migrations.AddIndex(
            model_name='reviewhelpful',
            index=models.Index(fields=['review', 'user'], name='reviews_rev_review__c11ee3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='reviewhelpful',
            unique_together={('review', 'user')},
        ),
    ]
